menu.create_content:
    path:     /create_content
    defaults: { _controller: WebBackBundle:Home:index }

menu.create_catalog:
    path:     /create_catalog
    defaults: { _controller: WebBackBundle:Home:catalog }

menu.admin_content:
    path:     /list_content
    defaults: { _controller: WebBackBundle:Content:index }

link.admin_content_by_id:
    path:     /{catalogId}/list_content
    defaults: { _controller: WebBackBundle:Content:index }

link.admin_edit_by_id:
    path:     /{id}/edit_content
    defaults: { _controller: WebBackBundle:Content:edit }