menu.lesson_index:
    path: /
    defaults: { _controller: WebBackBundle:Lesson:index }

link.lessson_edit:
    path: /{id}/edit
    defaults: { _controller: WebBackBundle:Lesson:index }

menu.lesson_list:
    path: /list
    defaults: { _controller: WebBackBundle:Lesson:list }

link.lesson_upload:
    path: /{id}/upload
    defaults: { _controller: WebBackBundle:Lesson:upload }

link.lesson_attachment_delete:
    path: /{attachmentId}/delete
    defaults: { _controller: WebBackBundle:Lesson:deleteAttachment }