menu.create_newsfeed:
    path:     /create_newsfeed
    defaults: { _controller: WebBackBundle:Newsfeed:create }

menu.list_newsfeed:
    path:     /list_newsfeed
    defaults: { _controller: WebBackBundle:Newsfeed:index }

link.edit_newsfeed:
    path:     /{id}/edit_newsfeed
    defaults: { _controller: WebBackBundle:Newsfeed:edit }

link.upload_newsfeed:
    path:     /{id}/newsfeed_upload
    defaults: { _controller: WebBackBundle:Newsfeed:upload }

link.unlink_attachment:
    path:     /{id}/unlink_attachment
    defaults: { _controller: WebBackBundle:Newsfeed:unlink }

link.remove_newsfeed:
    path:     /{id}/newsfeed_remove
    defaults: { _controller: WebBackBundle:Newsfeed:remove }

link.news_set_status:
    path: /{id}/newsfeed_status
    defaults: { _controller: WebBackBundle:Newsfeed:status }

menu.synchronize:
    path: /synchronize
    defaults: { _controller: WebBackBundle:Newsfeed:synchronize }