services:
    content_paginator:
        class: Web\BackBundle\Paginator\PaginatorFactory
        arguments: [@service_container , 'content_entity']

    newsfeed_paginator:
        class: Web\BackBundle\Paginator\PaginatorFactory
        arguments: [@service_container , 'newsfeed_entity']

    lesson_paginator:
        class: Web\BackBundle\Paginator\PaginatorFactory
        arguments: [@service_container , 'lesson_entity']

    case_paginator:
        class: Web\BackBundle\Paginator\PaginatorFactory
        arguments: [@service_container , 'case_entity']