services:
    content_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackBundle\Entity\Content ]

    newsfeed_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackBundle\Entity\Newsfeed ]

    attachment_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackBundle\Entity\Attachment ]