services:
    content_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackBundle\Entity\Content ]

    catalog_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackBundle\Entity\Catalog ]

    newsfeed_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackBundle\Entity\Newsfeed ]

    team_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackBundle\Entity\Team ]

    attachment_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackBundle\Entity\Attachment ]

    background_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackBundle\Entity\Background ]

    lesson_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackBundle\Entity\Lesson ]

    history_entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ Web\BackBundle\Entity\History ]