menu.home_page:
    path: /
    defaults: { _controller: WebBackBundle:Home:default }

newsfeed:
    resource: "@WebBackBundle/Resources/config/routing/newsfeed.yml"
    prefix:   /

content:
    resource: "@WebBackBundle/Resources/config/routing/content.yml"
    prefix:   /

team:
    resource: "@WebBackBundle/Resources/config/routing/team.yml"
    prefix:   /

lesson:
    resource: "@WebBackBundle/Resources/config/routing/lesson.yml"
    prefix:   /lesson

history:
    resource: "@WebBackBundle/Resources/config/routing/history.yml"
    prefix:   /history

rest_upload:
    path: /rest_upload
    defaults: { _controller: WebBackBundle:Upload:image }

background_upload:
    path: /background_upload
    defaults: { _controller: WebBackBundle:Upload:background }

active_background_upload:
    path: /{id}/active_background_upload
    defaults: { _controller: WebBackBundle:Upload:active }