imports:
    - { resource: factory.yml }
    - { resource: paginator.yml }

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
           - { name: twig.extension }

    twig.extension.vector:
        class: Web\BackBundle\Twig\BlockExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    attachment.manager:
        class: Web\BackBundle\Attachment\AttachmentManager
        arguments: [@service_container,@attachment_entity]

    rest_attachment.manager:
        class: Web\BackBundle\Attachment\RestAttachmentManager
        arguments: [ @kernel , @security.context , @request_stack , @doctrine , @attachment_entity]